### ISSUE TITLE
ModuleNotFoundError: No module named 'ibug.parsers._tree32'

### ISSUE THREAD

**Issue by tuanaqeelbohoran** [jjbrophy47/ibug#7] opened 2023-06-14 15:04 UTC
Hi, when i try to run the example code, I get the following error. can you help me solve it?

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-f8740768629c> in <module>
----> 1 from ibug import IBUGWrapper
      2 from xgboost import XGBRegressor
      3 from sklearn.datasets import load_diabetes
      4 from sklearn.model_selection import train_test_split
      5 

D:\PhD\code21-uncertinity\ibug-master\ibug\__init__.py in <module>
----> 1 from .classes import IBUGWrapper
      2 from .classes import KNNWrapper

D:\PhD\code21-uncertinity\ibug-master\ibug\classes.py in <module>
      9 from sklearn.preprocessing import StandardScaler
     10 
---> 11 from .base import Estimator
     12 from .parsers import util
     13 from .parsers.tree import Tree

D:\PhD\code21-uncertinity\ibug-master\ibug\base.py in <module>
      2 from abc import abstractmethod
      3 
----> 4 from .parsers import parse_model
      5 
      6 

D:\PhD\code21-uncertinity\ibug-master\ibug\parsers\__init__.py in <module>
      4 import numpy as np
      5 
----> 6 from .parser_cb import parse_cb_ensemble
      7 from .parser_lgb import parse_lgb_ensemble
      8 from .parser_sk import parse_skhgbm_ensemble

D:\PhD\code21-uncertinity\ibug-master\ibug\parsers\parser_cb.py in <module>
      6 import numpy as np
      7 
----> 8 from .tree import Tree
      9 
     10 

D:\PhD\code21-uncertinity\ibug-master\ibug\parsers\tree.py in <module>
      2 
      3 from . import util
----> 4 from ._tree32 import _Tree32
      5 from ._tree64 import _Tree64
      6 

ModuleNotFoundError: No module named 'ibug.parsers._tree32'

**Comment by jjbrophy47** [comment] 2023-06-15 03:54
Hi tunaqeelbohoran, can you tell me what version of `python`, `ibug`, and `xgboost` you are using, thanks!

**Comment by tuanaqeelbohoran** [comment] 2023-06-28 18:39
Hi I was able to solve the problem by compiling ".pyx" files.

But my next question is how do I check feature importance in the ibug model?

**Comment by jjbrophy47** [comment] 2023-06-29 03:28
Sorry for the slow response, but I'm glad you were able to resolve the issue.

IBUG is simply a wrapper around the original GBRT model. So, to get feature importance, you can just extract the feature importances from the original model. For example, if my GBRT model is an XGBoost regressor called `xgb_model`, then I would do the following:
```
feature_importances = xgb_model.feature_importances_
```

**Comment by joshdunnlime** [comment] 2024-02-14 09:59
Same issue using `pip install ibug`:
Mac M1
python 3.10
ibug 0.0.9

I fixed this by installing direct from github: `pip install https://github.com/jjbrophy47/ibug`.

It would be nice to fix this in pypi though.

**Comment by jjbrophy47** [comment] 2024-05-19 00:19
Unable to reproduce this error, closing issue.

**Closed by jjbrophy47** 2024-05-19 00:19 UTC
Labels: wontfix
